name: CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequea el código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js con la versión 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Especifica la versión de Node.js que deseas usar
          cache: 'npm'  # Opcional: Cache para npm

      # 3. Instala las dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecuta las pruebas con cobertura
      - name: Run tests with coverage
        run: npm run test:coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
